title: The Ram Project
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is project which shows events of Ramayana on map, and some additional information.
baseurl: "/the-ram-project-public" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
plugins:
  - jekyll-feed
